// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshJBoYKzbRsYGOSfVECxqpklLMskQwnw',
    appId: '1:825001338191:web:f9fac708b42d04563b913a',
    messagingSenderId: '825001338191',
    projectId: 'kaya-e1032',
    authDomain: 'kaya-e1032.firebaseapp.com',
    storageBucket: 'kaya-e1032.firebasestorage.app',
    measurementId: 'G-PY3WTK4EHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4NzIqQg0tLeL7RvwiRyZWTbh9vYa0XRE',
    appId: '1:825001338191:android:13e909e72e6c20223b913a',
    messagingSenderId: '825001338191',
    projectId: 'kaya-e1032',
    storageBucket: 'kaya-e1032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_5Bb54TDSjOXR2Li898U5y5f_OhBjgM',
    appId: '1:825001338191:ios:261e3196c8b767463b913a',
    messagingSenderId: '825001338191',
    projectId: 'kaya-e1032',
    storageBucket: 'kaya-e1032.firebasestorage.app',
    iosBundleId: 'com.example.kaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_5Bb54TDSjOXR2Li898U5y5f_OhBjgM',
    appId: '1:825001338191:ios:261e3196c8b767463b913a',
    messagingSenderId: '825001338191',
    projectId: 'kaya-e1032',
    storageBucket: 'kaya-e1032.firebasestorage.app',
    iosBundleId: 'com.example.kaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDshJBoYKzbRsYGOSfVECxqpklLMskQwnw',
    appId: '1:825001338191:web:7c27eb76672ec5783b913a',
    messagingSenderId: '825001338191',
    projectId: 'kaya-e1032',
    authDomain: 'kaya-e1032.firebaseapp.com',
    storageBucket: 'kaya-e1032.firebasestorage.app',
    measurementId: 'G-XWV2KW1TVQ',
  );
}
